Handle cases of "icon" object being null (license/trial stuff)
Got a console error just now:
TypeError: icon.data is not a function

Adding a safety check for this, does not hurt

Signed-off-by: falkTX <falktx@falktx.com>